### ISSUE TITLE
Feature Request: Support for Multiple Static Prompts in Writing Assistant

### ISSUE THREAD

**Issue by gldh-gh** [chrisgrieser/alfred-writing-assistant#5]
### Feature Requested

Currently, the Writing Assistant allows for the use of a single static_prompt as part of its configuration. While this feature is quite useful, I believe the product could benefit from supporting multiple static prompts. Specifically, it would be great to have additional options like `static_prompt_rewrite`, `static_prompt_email`, and so on.

For example:

`static_prompt_rewrite`: A prompt tailored for rewriting existing text to improve clarity, tone, or style.
`static_prompt_email`: A prompt specifically designed for rewriting emails to ensure they are concise, professional, and aligned with the intended tone.
These additional prompts would allow users to define and switch between different static prompts more easily, making the tool more adaptable to varied writing scenarios. This could enable more nuanced configurations, such as assigning different static prompts for different stages of content creation or different types of writing tasks.

Thank you for considering this request. I'm confident that this feature would add significant value to the Writing Assistant, and I look forward to your feedback.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
ngl, this FR does sound a bit like it was written by an AI… This is an open source project which I do in my free time for others for free, not a "product".

> While this feature is quite useful, I believe **the product** could benefit from supporting multiple static prompts.

**Comment by chrisgrieser** [comment]
Thank you for the request, but I think it is a bit out of scope for this plugin. There are various other Alfred workflows for using AI, which are much more feature-rich and better suited for this kind of feature (if they do not have such a feature already).
